export const SETSOCKETROOM = "SETSOCKETROOM";
export const DELSOCKETROOM = "DELSOCKETROOM";
export const SETCURRENTROOM = "SETCURRENTSOCKETROOM";
export const UPDATEMESSAGE = "UPDATEMESSAGE";
export const SETVIDEOROOM = "SETVIDEOROOM";
export const STOPVIDEOROOM = "STOPVIDEOROOM";
